"""empty message

Revision ID: 49688ce1cc04
Revises: 
Create Date: 2021-02-09 22:31:53.579027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49688ce1cc04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=63), nullable=False),
    sa.Column('descricao', sa.String(length=127), nullable=True),
    sa.Column('qnt_estoque', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('produtos')
    op.add_column('servico', sa.Column('nome', sa.String(length=63), nullable=False))
    op.drop_column('servico', 'servico')
    op.add_column('usuario', sa.Column('email', sa.String(length=63), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'email')
    op.add_column('servico', sa.Column('servico', sa.VARCHAR(length=63), nullable=False))
    op.drop_column('servico', 'nome')
    op.create_table('produtos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=63), nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=127), nullable=True),
    sa.Column('qnt_estoque', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('produto')
    # ### end Alembic commands ###
