"""empty message

Revision ID: 721424efafed
Revises: 
Create Date: 2021-02-11 13:01:36.475967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721424efafed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=63), nullable=False),
    sa.Column('descricao', sa.String(length=127), nullable=True),
    sa.Column('qnt_estoque', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=63), nullable=False),
    sa.Column('senha', sa.String(length=63), nullable=False),
    sa.Column('nome', sa.String(length=63), nullable=False),
    sa.Column('endereco', sa.String(length=127), nullable=False),
    sa.Column('email', sa.String(length=63), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=63), nullable=True),
    sa.Column('raca', sa.String(length=63), nullable=False),
    sa.Column('porte', sa.String(length=63), nullable=False),
    sa.Column('data_nascimento', sa.String(length=63), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=63), nullable=False),
    sa.Column('horario', sa.String(length=20), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=127), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('van',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario', sa.String(length=20), nullable=False),
    sa.Column('id_pet', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=127), nullable=True),
    sa.ForeignKeyConstraint(['id_pet'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('van')
    op.drop_table('servico')
    op.drop_table('pet')
    op.drop_table('usuario')
    op.drop_table('produto')
    # ### end Alembic commands ###
